// USER
export const GET_USER_START   = "GET_USER_START";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL    = "GET_USER_FAIL";

export const GET_IOT_TOKEN_START   = "GET_IOT_TOKEN_START";
export const GET_IOT_TOKEN_SUCCESS = "GET_IOT_TOKEN_SUCCESS";
export const GET_IOT_TOKEN_FAIL    = "GET_IOT_TOKEN_FAIL";

// AUTH
export const AUTH_LOGOUT = "AUTH_LOGOUT";

// PLANT
export const GET_PLANT_START   = "GET_PLANT_START";
export const GET_PLANT_SUCCESS = "GET_PLANT_SUCCESS";
export const GET_PLANT_FAIL    = "GET_PLANT_FAIL";

// SETTING USERS
export const GET_SETTING_USER_PROGRESS_PLANT_START   = "GET_SETTING_USER_PROGRESS_PLANT_START";
export const GET_SETTING_USER_PROGRESS_PLANT_SUCCESS = "GET_SETTING_USER_PROGRESS_PLANT_SUCCESS";
export const GET_SETTING_USER_PROGRESS_PLANT_FAIL    = "GET_SETTING_USER_PROGRESS_PLANT_FAIL";

export const GET_SETTING_USER_MY_SETTING_START   = "GET_SETTING_USER_SETTING_START";
export const GET_SETTING_USER_MY_SETTING_SUCCESS = "GET_SETTING_USER_SETTING_SUCCESS";
export const GET_SETTING_USER_MY_SETTING_FAIL    = "GET_SETTING_USER_SETTING_FAIL";

// REPORT
export const GET_ALL_REPORTS_START   = "GET_ALL_REPORTS_START"
export const GET_ALL_REPORTS_SUCCESS = "GET_ALL_REPORTS_SUCCESS"
export const GET_ALL_REPORTS_FAIL    = "GET_ALL_REPORTS_FAIL"

export const GET_PH_CHART_REPORT_START   = "GET_PH_CHART_REPORT_START"
export const GET_PH_CHART_REPORT_SUCCESS = "GET_PH_CHART_REPORT_SUCCESS"
export const GET_PH_CHART_REPORT_FAIL    = "GET_PH_CHART_REPORT_FAIL"

export const GET_TDS_CHART_REPORT_START   = "GET_TDS_CHART_REPORT_START"
export const GET_TDS_CHART_REPORT_SUCCESS = "GET_TDS_CHART_REPORT_SUCCESS"
export const GET_TDS_CHART_REPORT_FAIL    = "GET_TDS_CHART_REPORT_FAIL"

export const GET_GROWTH_PLANT_CHART_REPORT_START   = "GET_GROWTH_PLANT_CHART_REPORT_START"
export const GET_GROWTH_PLANT_CHART_REPORT_SUCCESS = "GET_GROWTH_PLANT_CHART_REPORT_SUCCESS"
export const GET_GROWTH_PLANT_CHART_REPORT_FAIL    = "GET_GROWTH_PLANT_CHART_REPORT_FAIL"

export const GET_ALERT_REPORT_START   = "GET_ALERT_REPORT_START"
export const GET_ALERT_REPORT_SUCCESS = "GET_ALERT_REPORT_SUCCESS"
export const GET_ALERT_REPORT_FAIL    = "GET_ALERT_REPORT_FAIL"

// BLOG
export const GET_BLOG_START   = "GET_BLOG_START";
export const GET_BLOG_SUCCESS = "GET_BLOG_SUCCESS";
export const GET_BLOG_FAIL    = "GET_BLOG_FAIL";

// CATEGORY
export const GET_CATEGORY_START   = "GET_CATEGORY_START";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAIL    = "GET_CATEGORY_FAIL";

// DOCUMENTATION
export const GET_ALL_DOCUMENTATION_START   = "GET_ALL_DOCUMENTATION_START";
export const GET_ALL_DOCUMENTATION_SUCCESS = "GET_ALL_DOCUMENTATION_SUCCESS";
export const GET_ALL_DOCUMENTATION_FAIL    = "GET_ALL_DOCUMENTATION_FAIL";
