// USER
export const GET_USER_START   = "GET_USER_START";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL    = "GET_USER_FAIL";

export const GET_IOT_TOKEN_START   = "GET_IOT_TOKEN_START";
export const GET_IOT_TOKEN_SUCCESS = "GET_IOT_TOKEN_SUCCESS";
export const GET_IOT_TOKEN_FAIL    = "GET_IOT_TOKEN_FAIL";

// AUTH
export const AUTH_LOGOUT = "AUTH_LOGOUT";

// PLANT
export const GET_PLANT_START   = "GET_PLANT_START";
export const GET_PLANT_SUCCESS = "GET_PLANT_SUCCESS";
export const GET_PLANT_FAIL    = "GET_PLANT_FAIL";

// SETTING USERS
export const GET_SETTING_USER_PROGRESS_PLANT_START   = "GET_SETTING_USER_PROGRESS_PLANT_START";
export const GET_SETTING_USER_PROGRESS_PLANT_SUCCESS = "GET_SETTING_USER_PROGRESS_PLANT_SUCCESS";
export const GET_SETTING_USER_PROGRESS_PLANT_FAIL    = "GET_SETTING_USER_PROGRESS_PLANT_FAIL";

export const GET_SETTING_USER_MY_SETTING_START   = "GET_SETTING_USER_SETTING_START";
export const GET_SETTING_USER_MY_SETTING_SUCCESS = "GET_SETTING_USER_SETTING_SUCCESS";
export const GET_SETTING_USER_MY_SETTING_FAIL    = "GET_SETTING_USER_SETTING_FAIL";
